-- Seed data for the `universities` table (Institute entity).
--
-- Source: University Grants Commission / Bangladesh Medical & Dental Council
-- listings as compiled on Wikipedia (List of universities in Bangladesh,
-- List of medical colleges in Bangladesh).
--
-- Runs on every startup (spring.sql.init.mode=always) and is idempotent:
-- existing ids are left untouched, so manual edits and soft deletes survive.
-- IDs 1-298 are reserved for this seed; start new institutes at 299.


-- Public universities (57)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (1, 'Aviation and Aerospace University Bangladesh', 'AAUB', 'http://bsmraau.edu.bd', now(), now(), false),
    (2, 'Bangladesh Agricultural University', 'BAU', 'http://bau.edu.bd', now(), now(), false),
    (3, 'Bangladesh Maritime University', 'BMU', 'http://bsmrmu.edu.bd', now(), now(), false),
    (4, 'Bangladesh Open University', 'BOU', 'http://bou.ac.bd', now(), now(), false),
    (5, 'Bangladesh University of Engineering and Technology', 'BUET', 'https://www.buet.ac.bd', now(), now(), false),
    (6, 'Bangladesh University of Professionals', 'BUP', 'http://bup.edu.bd', now(), now(), false),
    (7, 'Bangladesh University of Textiles', 'BUTEX', 'http://butex.edu.bd', now(), now(), false),
    (8, 'Begum Rokeya University', 'BRUR', 'http://brur.ac.bd', now(), now(), false),
    (9, 'Chandpur Science and Technology University', 'CSTU', 'http://cstu.ac.bd', now(), now(), false),
    (10, 'Chittagong University of Engineering and Technology', 'CUET', 'http://www.cuet.ac.bd', now(), now(), false),
    (11, 'Chittagong Veterinary and Animal Sciences University', 'CVASU', 'http://cvasu.ac.bd', now(), now(), false),
    (12, 'Comilla University', 'CoU', 'http://cou.ac.bd', now(), now(), false),
    (13, 'Dhaka Central University', 'DCU', 'http://dcu.ac.bd', now(), now(), false),
    (14, 'Dhaka University of Engineering and Technology', 'DUET', 'http://duet.ac.bd', now(), now(), false),
    (15, 'Gazipur Agricultural University', 'GAU', 'https://bsmrau.edu.bd', now(), now(), false),
    (16, 'Gopalganj Science and Technology University', 'GSTU', 'http://www.bsmrstu.edu.bd', now(), now(), false),
    (17, 'Habiganj Agricultural University', 'HAU', 'http://hau.ac.bd', now(), now(), false),
    (18, 'Hajee Mohammad Danesh Science and Technology University', 'HSTU', 'http://hstu.ac.bd', now(), now(), false),
    (19, 'Islamic Arabic University', 'IAU', 'http://iau.edu.bd', now(), now(), false),
    (20, 'Islamic University, Bangladesh', 'IU', 'http://iu.ac.bd', now(), now(), false),
    (21, 'Jagannath University', 'JnU', 'http://jnu.ac.bd', now(), now(), false),
    (22, 'Jahangirnagar University', 'JU', 'https://juniv.edu', now(), now(), false),
    (23, 'Jamalpur Science and Technology University', 'JSTU', 'http://bsfmstu.ac.bd', now(), now(), false),
    (24, 'Jashore University of Science and Technology', 'JUST', 'http://just.edu.bd', now(), now(), false),
    (25, 'Jatiya Kabi Kazi Nazrul Islam University', 'JKKNIU', 'http://jkkniu.edu.bd', now(), now(), false),
    (26, 'Khulna Agricultural University', 'KAU', 'http://kau.edu.bd', now(), now(), false),
    (27, 'Khulna University', 'KU', 'http://ku.ac.bd', now(), now(), false),
    (28, 'Khulna University of Engineering and Technology', 'KUET', 'http://kuet.ac.bd', now(), now(), false),
    (29, 'Kishoreganj University', 'KgU', 'https://bsmru.ac.bd', now(), now(), false),
    (30, 'Kurigram Agricultural University', 'KuriAU', 'https://kuriau.edu.bd', now(), now(), false),
    (31, 'Lakshmipur Science and Technology University', 'LSTU', NULL, now(), now(), false),
    (32, 'Mawlana Bhashani Science and Technology University', 'MBSTU', 'http://mbstu.ac.bd', now(), now(), false),
    (33, 'Meherpur University', 'MU', 'https://www.mum.ac.bd', now(), now(), false),
    (34, 'Military Institute of Science and Technology', 'MIST', 'https://mist.ac.bd', now(), now(), false),
    (35, 'Narayanganj Science and Technology University', 'NGSTU', NULL, now(), now(), false),
    (36, 'National University Bangladesh', 'NU', 'http://www.nu.ac.bd', now(), now(), false),
    (37, 'Netrokona University', 'NkU', 'https://www.shu.edu.bd', now(), now(), false),
    (38, 'Noakhali Science and Technology University', 'NSTU', 'http://nstu.edu.bd', now(), now(), false),
    (39, 'Pabna University of Science and Technology', 'PUST', 'http://www.pust.ac.bd', now(), now(), false),
    (40, 'Patuakhali Science and Technology University', 'PSTU', 'http://pstu.ac.bd', now(), now(), false),
    (41, 'Pirojpur Science and Technology University', 'PrSTU', 'https://www.bsmrstup.ac.bd', now(), now(), false),
    (42, 'Rabindra University, Bangladesh', 'RUB', 'http://www.rub.ac.bd', now(), now(), false),
    (43, 'Rajshahi University of Engineering and Technology', 'RUET', 'http://www.ruet.ac.bd', now(), now(), false),
    (44, 'Rangamati Science and Technology University', 'RmSTU', 'http://rmstu.edu.bd', now(), now(), false),
    (45, 'Satkhira University of Science and Technology', 'SaUST', NULL, now(), now(), false),
    (46, 'Shahjalal University of Science and Technology', 'SUST', 'http://www.sust.edu', now(), now(), false),
    (47, 'Shariatpur Agriculture University', 'ShAU', NULL, now(), now(), false),
    (48, 'Sher-e-Bangla Agricultural University', 'SBAU', 'http://sau.edu.bd', now(), now(), false),
    (49, 'Sunamganj Science and Technology University', 'SSTU', 'https://sstu.ac.bd', now(), now(), false),
    (50, 'Sylhet Agricultural University', 'SAU', 'http://sau.ac.bd', now(), now(), false),
    (51, 'Thakurgaon University', 'TU', NULL, now(), now(), false),
    (52, 'University of Barisal', 'BU', 'http://bu.ac.bd', now(), now(), false),
    (53, 'University of Bogura', 'UB', 'https://www.bstu.ac.bd', now(), now(), false),
    (54, 'University of Chittagong', 'CU', 'https://web.cu.ac.bd/v2', now(), now(), false),
    (55, 'University of Dhaka', 'DU', 'https://www.du.ac.bd', now(), now(), false),
    (56, 'University of Frontier Technology, Bangladesh', 'UFTB', 'https://bdu.ac.bd', now(), now(), false),
    (57, 'University of Rajshahi', 'RU', 'http://ru.ac.bd', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Public medical universities (5)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (58, 'Bangladesh Medical University', 'BMU', 'http://bsmmu.edu.bd', now(), now(), false),
    (59, 'Chittagong Medical University', 'CMU', 'http://cmu.edu.bd', now(), now(), false),
    (60, 'Khulna Medical University', 'KMU', 'https://shmu.ac.bd', now(), now(), false),
    (61, 'Rajshahi Medical University', 'RMU', 'http://www.rmu.edu.bd', now(), now(), false),
    (62, 'Sylhet Medical University', 'SMU', 'https://smu.edu.bd', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Public medical colleges (38)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (63, 'Chandpur Medical College', 'ChMC', 'https://chmc.college.gov.bd', now(), now(), false),
    (64, 'Chittagong Medical College', 'CMC', 'https://cmc.gov.bd', now(), now(), false),
    (65, 'Cox''s Bazar Medical College', 'CoxMC', 'http://coxmc.edu.bd', now(), now(), false),
    (66, 'Cumilla Medical College', 'CuMC', 'https://cumc.edu.bd', now(), now(), false),
    (67, 'Dhaka Medical College', 'DMC', 'https://dmch.gov.bd', now(), now(), false),
    (68, 'Dinajpur Medical College', 'DjMC', 'https://marmcd.edu.bd', now(), now(), false),
    (69, 'Faridpur Medical College', 'FMC', 'https://bsmmc.edu.bd', now(), now(), false),
    (70, 'Gopalganj Medical College', 'GGMC', 'https://www.ggmc.edu.bd', now(), now(), false),
    (71, 'Habiganj Medical College', 'HMC', 'https://habiganjmedicalcollege.firebaseapp.com', now(), now(), false),
    (72, 'Jamalpur Medical College', 'JpMC', NULL, now(), now(), false),
    (73, 'Jashore Medical College', 'JMC', NULL, now(), now(), false),
    (74, 'Khulna Medical College', 'KMC', 'https://kmc.gov.bd', now(), now(), false),
    (75, 'Kushtia Medical College', 'KuMC', 'https://www.kumc.edu.bd', now(), now(), false),
    (76, 'Magura Medical College', 'MaMC', 'https://maguramc.edu.bd', now(), now(), false),
    (77, 'Manikganj Medical College', 'MkMC', 'https://www.cmmc.gov.bd', now(), now(), false),
    (78, 'Mugda Medical College', 'MuMC', 'http://mumc.gov.bd', now(), now(), false),
    (79, 'Mymensingh Medical College', 'MMC', 'https://www.mmc.gov.bd', now(), now(), false),
    (80, 'Naogaon Medical College', 'NaMC', 'http://naogaonmedical.naogaon.gov.bd', now(), now(), false),
    (81, 'Netrokona Medical College, Netrokona', 'NMC', NULL, now(), now(), false),
    (82, 'Nilphamari Medical College', 'NpMC', NULL, now(), now(), false),
    (83, 'Noakhali Medical College', 'NMC', NULL, now(), now(), false),
    (84, 'Pabna Medical College', 'PMC', 'https://medicalcollege.pabna.gov.bd', now(), now(), false),
    (85, 'Patuakhali Medical College', 'PkMC', 'https://pkmc.college.gov.bd', now(), now(), false),
    (86, 'Rajshahi Medical College', 'RMC', 'https://rmc.gov.bd', now(), now(), false),
    (87, 'Rangamati Medical College', 'RmMC', 'http://rangamatimc.edu.bd', now(), now(), false),
    (88, 'Rangpur Medical College', 'RpMC', 'https://rpmc.edu.bd', now(), now(), false),
    (89, 'Satkhira Medical College', 'SMC', NULL, now(), now(), false),
    (90, 'Shaheed Suhrawardy Medical College', 'ShSMC', 'https://www.shsmc.gov.bd', now(), now(), false),
    (91, 'Shaheed Tajuddin Ahmad Medical College', 'STAMC', 'https://stamc.edu.bd', now(), now(), false),
    (92, 'Shaheed Ziaur Rahman Medical College', 'SZMC', 'https://szmc.gov.bd', now(), now(), false),
    (93, 'Shahid Syed Nazrul Islam Medical College', 'SSNIMC', 'https://www.ssnimc.gov.bd', now(), now(), false),
    (94, 'Sher-e-Bangla Medical College', 'SBMC', 'https://www.sbmc.edu.bd', now(), now(), false),
    (95, 'Sir Salimullah Medical College', 'SSMC', 'https://ssmcmh.gov.bd', now(), now(), false),
    (96, 'Sirajganj Medical College', 'SjMC', 'https://www.smmamc.gov.bd', now(), now(), false),
    (97, 'Sunamganj Medical College', 'SuMC', 'https://bbmcs.edu.bd', now(), now(), false),
    (98, 'Sylhet MAG Osmani Medical College', 'SOMC', 'https://somc.college.gov.bd', now(), now(), false),
    (99, 'Tangail Medical College', 'TMC', NULL, now(), now(), false),
    (100, 'Thakurgaon Medical College', 'TAMC', NULL, now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Public engineering colleges (13)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (101, 'Barisal Engineering College', 'BEC', 'http://barisal-eng.portal.gov.bd', now(), now(), false),
    (102, 'Barishal Textile Engineering College', 'BTEC', 'https://www.sarstec.com', now(), now(), false),
    (103, 'Faridpur Engineering College', 'FEC', 'http://fec.ac.bd', now(), now(), false),
    (104, 'Gopalganj Textile Engineering College', 'GTEC', 'https://www.srtec.gov.bd', now(), now(), false),
    (105, 'Jamalpur Textile Engineering College', 'JTEC', 'https://jtec-jamalpurgovtex.com', now(), now(), false),
    (106, 'Jhenaidah Textile Engineering College, Jhenaidah', 'JTEC', 'https://sktec.jhenaidah.gov.bd', now(), now(), false),
    (107, 'Mymensingh Engineering College', 'MEC', 'http://mec.ac.bd', now(), now(), false),
    (108, 'Pabna Textile Engineering College', 'PTEC', 'https://www.pabtec.gov.bd', now(), now(), false),
    (109, 'Rangpur Textile Engineering College', 'RTEC', 'http://dwmtec.pirgonj.rangpur.gov.bd', now(), now(), false),
    (110, 'Sylhet Engineering College', 'SEC', 'http://sec.ac.bd', now(), now(), false),
    (111, 'Tangail Textile Engineering College, Tangail', 'TTEC', 'https://btec.portal.gov.bd', now(), now(), false),
    (112, 'Textile Engineering College, Chittagong', 'CTEC', 'https://ctec.chittagong.gov.bd', now(), now(), false),
    (113, 'Textile Engineering College, Noakhali', 'TECN', 'https://www.tecn.gov.bd', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- International universities (2)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (114, 'Asian University for Women', 'AUW', 'https://asian-university.org', now(), now(), false),
    (115, 'Islamic University of Technology', 'IUT', 'http://www.iutoic-dhaka.edu', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Private universities (108)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (116, 'Ahsanullah University of Science and Technology', 'AUST', 'http://www.aust.edu', now(), now(), false),
    (117, 'American International University-Bangladesh', 'AIUB', 'https://www.aiub.edu', now(), now(), false),
    (118, 'Anwer Khan Modern University', 'AKMU', 'https://akmu.edu.bd', now(), now(), false),
    (119, 'Asa University Bangladesh', 'ASAUB', 'http://www.asaub.edu.bd', now(), now(), false),
    (120, 'Asian University of Bangladesh', 'AUB', 'http://www.aub.edu.bd', now(), now(), false),
    (121, 'Atish Dipankar University of Science and Technology', 'ADUST', 'http://www.adust.edu.bd', now(), now(), false),
    (122, 'Bandarban University', 'BdU', 'https://bubban.edu.bd', now(), now(), false),
    (123, 'Bangladesh Army International University of Science and Technology', 'BAIUST', 'http://www.baiust.edu.bd', now(), now(), false),
    (124, 'Bangladesh Army University of Engineering and Technology', 'BAUET', 'http://bauet.ac.bd', now(), now(), false),
    (125, 'Bangladesh Army University of Science and Technology, Khulna', 'BAUST, Khulna', 'https://baustkhulna.ac.bd', now(), now(), false),
    (126, 'Bangladesh Army University of Science and Technology, Saidpur', 'BAUST, Saidpur', 'http://baust.edu.bd', now(), now(), false),
    (127, 'Bangladesh Islami University', 'BIU', 'http://www.biu.ac.bd', now(), now(), false),
    (128, 'Bangladesh University', 'BU', 'http://bu.edu.bd', now(), now(), false),
    (129, 'Bangladesh University of Business and Technology', 'BUBT', 'http://www.bubt.edu.bd', now(), now(), false),
    (130, 'Bangladesh University of Health Sciences', 'BUHS', 'http://buhs.ac.bd', now(), now(), false),
    (131, 'BGC Trust University Bangladesh', 'BGCTUB', 'http://bgctub.ac.bd', now(), now(), false),
    (132, 'BGMEA University of Fashion and Technology', 'BUFT', 'https://buft.edu.bd', now(), now(), false),
    (133, 'Brac University', 'BracU', 'http://www.bracu.ac.bd', now(), now(), false),
    (134, 'Brahmaputra International University', 'BIU', 'http://www.sfmuniversity.org', now(), now(), false),
    (135, 'Britannia University', 'BU', 'http://britannia.edu.bd', now(), now(), false),
    (136, 'Canadian University of Bangladesh', 'CUB', 'http://cub.edu.bd', now(), now(), false),
    (137, 'CCN University of Science and Technology', 'CCNUST', 'https://ccnust.ac.bd', now(), now(), false),
    (138, 'Central University of Science and Technology', 'CUST', 'http://cust.edu.bd', now(), now(), false),
    (139, 'Central Women''s University', 'CWU', 'http://www.cwu.edu.bd', now(), now(), false),
    (140, 'Chittagong Independent University', 'CIU', 'http://ciu.edu.bd', now(), now(), false),
    (141, 'City University, Bangladesh', 'CUB', 'http://cityuniversity.edu.bd', now(), now(), false),
    (142, 'Cox''s Bazar International University', 'CBIU', 'http://www.cbiu.ac.bd', now(), now(), false),
    (143, 'Daffodil International University', 'DIU', 'http://daffodilvarsity.edu.bd', now(), now(), false),
    (144, 'Dhaka International University', 'DIU', 'http://diu.ac', now(), now(), false),
    (145, 'Dr. Momtaz Begum University of Science and Technology', 'MUST', 'http://must.ac.bd', now(), now(), false),
    (146, 'East Delta University', 'EDU', 'https://www.eastdelta.edu.bd', now(), now(), false),
    (147, 'East West University', 'EWU', 'http://www.ewubd.edu', now(), now(), false),
    (148, 'Eastern University, Bangladesh', 'EU', 'http://www.easternuni.edu.bd', now(), now(), false),
    (149, 'European University of Bangladesh', 'EUB', 'http://eub.edu.bd', now(), now(), false),
    (150, 'Exim Bank Agricultural University Bangladesh', 'EBAUB', 'http://www.ebaub.edu.bd', now(), now(), false),
    (151, 'Fareast International University', 'FIU', 'http://www.fiu.edu.bd', now(), now(), false),
    (152, 'Feni University', 'FU', 'http://feniuniversity.edu.bd', now(), now(), false),
    (153, 'First Capital University Of Bangladesh', 'FCUB', 'http://fcub.edu.bd', now(), now(), false),
    (154, 'German University Bangladesh', 'GUB', 'https://gub.edu.bd', now(), now(), false),
    (155, 'Global University Bangladesh', 'GUB', 'http://globaluniversity.edu.bd', now(), now(), false),
    (156, 'Gono Bishwabidyalay', 'GB', 'https://www.gonouniversity.edu.bd', now(), now(), false),
    (157, 'Grameen University', 'GU', 'https://grameenu.ac', now(), now(), false),
    (158, 'Green University of Bangladesh', 'GUB', 'http://green.edu.bd', now(), now(), false),
    (159, 'Hamdard University Bangladesh', 'HUB', 'http://hamdarduniversity.edu.bd', now(), now(), false),
    (160, 'IBAIS University', 'IU', 'http://www.ibaisuniv.edu.bd', now(), now(), false),
    (161, 'Independent University, Bangladesh', 'IUB', 'http://www.iub.edu.bd', now(), now(), false),
    (162, 'International Islami University of Science and Technology Bangladesh', 'IIUSTB', 'https://www.iiustb.ac.bd', now(), now(), false),
    (163, 'International Islamic University, Chittagong', 'IIUC', 'http://www.iiuc.ac.bd', now(), now(), false),
    (164, 'International Standard University', 'ISU', 'http://www.isu.ac.bd', now(), now(), false),
    (165, 'International University of Business Agriculture and Technology', 'IUBAT', 'http://www.iubat.edu', now(), now(), false),
    (166, 'Ishakha International University', 'IIUB', 'http://www.ishakha.edu.bd', now(), now(), false),
    (167, 'Khulna Khan Bahadur Ahsanullah University', 'KKBAU', 'https://www.kkbau.ac.bd', now(), now(), false),
    (168, 'Khwaja Yunus Ali University', 'KYAU', 'http://www.kyau.edu.bd', now(), now(), false),
    (169, 'Lalon University of Science and Arts', 'LUSA', 'https://www.lusa.ac.bd', now(), now(), false),
    (170, 'Leading University', 'LU', 'http://lus.ac.bd', now(), now(), false),
    (171, 'Manarat International University', 'MIU', 'http://www.manarat.ac.bd', now(), now(), false),
    (172, 'Metropolitan University', 'MU', 'http://metrouni.edu.bd', now(), now(), false),
    (173, 'Microland University of Science and Technology', 'MUST', 'https://www.microlanduniversity.org', now(), now(), false),
    (174, 'Millennium University', 'MU', 'http://www.themillenniumuniversity.edu.bd', now(), now(), false),
    (175, 'North Bengal International University', 'NBIU', 'https://www.nbiu.edu.bd', now(), now(), false),
    (176, 'North East University Bangladesh', 'NEUB', 'http://neub.edu.bd', now(), now(), false),
    (177, 'North South University', 'NSU', 'http://www.northsouth.edu', now(), now(), false),
    (178, 'North Western University, Bangladesh', 'NWU', 'http://nwu.edu.bd', now(), now(), false),
    (179, 'Northern University of Business and Technology Khulna', 'NUB', 'https://nubtkhulna.ac.bd', now(), now(), false),
    (180, 'Northern University, Bangladesh', 'NUB', 'http://nub.ac.bd', now(), now(), false),
    (181, 'Notre Dame University Bangladesh', 'NDUB', 'http://ndub.edu.bd', now(), now(), false),
    (182, 'NPI University of Bangladesh', 'NPIUB', 'https://www.npiub.edu.bd', now(), now(), false),
    (183, 'People''s University of Bangladesh', 'PUB', 'http://pub.ac.bd', now(), now(), false),
    (184, 'Port City International University', 'PCIU', 'https://www.portcity.edu.bd', now(), now(), false),
    (185, 'Premier University, Chittagong', 'PU', 'http://puc.ac.bd', now(), now(), false),
    (186, 'Presidency University', 'PU', 'http://presidency.edu.bd', now(), now(), false),
    (187, 'Prime University', 'PU', 'https://www.primeuniversity.edu.bd', now(), now(), false),
    (188, 'Primeasia University', 'PAU', 'http://primeasia.edu.bd', now(), now(), false),
    (189, 'Pundra University of Science and Technology', 'PDUST', 'http://www.pundrouniversity.edu.bd', now(), now(), false),
    (190, 'Queens University', 'QU', 'http://queensuniversity.edu.bd', now(), now(), false),
    (191, 'Rabindra Maitree University', 'RMU', 'https://rmu.ac.bd', now(), now(), false),
    (192, 'Rajshahi Science and Technology University', 'RSTU', 'http://rstu.edu.bd', now(), now(), false),
    (193, 'Ranada Prasad Shaha University', 'RPSU', 'http://www.rpsu.edu.bd', now(), now(), false),
    (194, 'Royal University of Dhaka', 'RUD', 'http://www.royal.edu.bd', now(), now(), false),
    (195, 'RTM Al-Kabir Technical University', 'RTM-AKTU', 'http://www.rtm-aktu.edu.bd', now(), now(), false),
    (196, 'Shanto-Mariam University of Creative Technology', 'SMUCT', 'http://smuct.edu.bd', now(), now(), false),
    (197, 'Sonargaon University', 'SU', 'http://su.edu.bd', now(), now(), false),
    (198, 'Southeast University', 'SEU', 'http://www.seu.edu.bd', now(), now(), false),
    (199, 'Southern University, Bangladesh', 'SUB', 'http://www.southern.edu.bd', now(), now(), false),
    (200, 'Stamford University Bangladesh', 'SU', 'https://stamforduniversity.edu.bd', now(), now(), false),
    (201, 'State University of Bangladesh', 'SUB', 'http://sub.edu.bd', now(), now(), false),
    (202, 'Sylhet International University', 'SIU', 'http://siu.edu.bd', now(), now(), false),
    (203, 'Tagore University of Creative Arts', 'TUCA', 'https://www.tuca.edu.bd', now(), now(), false),
    (204, 'Times University Bangladesh', 'TMUB', 'http://timesuniversitybd.com', now(), now(), false),
    (205, 'Trust University, Barishal', 'TUB', 'https://trustuniversity.edu.bd', now(), now(), false),
    (206, 'United International University', 'UIU', 'http://uiu.ac.bd', now(), now(), false),
    (207, 'University of Asia Pacific (Bangladesh)', 'UAP', 'http://www.uap-bd.edu', now(), now(), false),
    (208, 'University of Brahmanbaria', 'UOB', 'https://uob.edu.bd', now(), now(), false),
    (209, 'University of Creative Technology Chittagong', 'UCTC', 'http://www.uctc.edu.bd', now(), now(), false),
    (210, 'University of Development Alternative', 'UODA', 'http://uoda.edu.bd', now(), now(), false),
    (211, 'University of Global Village', 'UIGV', 'http://ugv.edu.bd', now(), now(), false),
    (212, 'University of Information Technology and Sciences', 'UITS', 'http://uits.edu.bd', now(), now(), false),
    (213, 'University of Liberal Arts Bangladesh', 'ULAB', 'http://ulab.edu.bd', now(), now(), false),
    (214, 'University of Scholars', 'IUS', 'https://ius.edu.bd', now(), now(), false),
    (215, 'University of Science and Technology Chittagong', 'USTC', 'http://ustc.ac.bd', now(), now(), false),
    (216, 'University of Skill Enrichment and Technology', 'USET', 'http://uset.edu.bd', now(), now(), false),
    (217, 'University of South Asia, Bangladesh', 'USAB', 'http://southasiauni.edu.bd', now(), now(), false),
    (218, 'Uttara University', 'UU', 'http://uttarauniversity.edu.bd', now(), now(), false),
    (219, 'Varendra University', 'VU', 'http://vu.edu.bd', now(), now(), false),
    (220, 'Victoria University of Bangladesh', 'VUB', 'http://vub.edu.bd', now(), now(), false),
    (221, 'World University of Bangladesh', 'WUB', 'http://www.wub.edu.bd', now(), now(), false),
    (222, 'ZH Sikder University of Science and Technology', 'ZHSUST', 'https://zhsust.edu.bd', now(), now(), false),
    (223, 'ZNRF University of Management Sciences', 'ZUMS', 'http://www.zums.edu.bd', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Private medical colleges (68)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (224, 'Ad-Din Akij Medical College', 'AAMC', 'http://ad-din.org/ad-din-akij-medical-college-aamc-khulna/about-aamc', now(), now(), false),
    (225, 'Ad-din Sakina Medical College', 'ASMC', 'http://ad-din.org/ad-din-sakina-medical-college-jessore/about-asmc', now(), now(), false),
    (226, 'Ad-din Women''s Medical College', 'AWMC', 'http://ad-din.org/addin-women-medical-college-awmc-dhaka/about-awmc', now(), now(), false),
    (227, 'Ahsania Mission Medical College', 'AMMC', 'https://ammch.edu.bd', now(), now(), false),
    (228, 'Aichi Medical College', 'AIMC', 'http://www.aichimedicalcollege.com', now(), now(), false),
    (229, 'Anwer Khan Modern Medical College', 'AKMMC', 'http://akmmc.edu.bd', now(), now(), false),
    (230, 'Asgar Ali Medical College', 'AAMC', 'http://www.asgaralimc.edu.bd', now(), now(), false),
    (231, 'Ashiyan Medical College', 'AMC', 'https://www.amchbd.com', now(), now(), false),
    (232, 'Bangladesh Medical College', 'BMCH', 'https://www.bmc-bd.org', now(), now(), false),
    (233, 'Barind Medical College', 'BMC', 'http://bmcraj.org', now(), now(), false),
    (234, 'Bashundhara Ad-din Medical College', 'BAMC', 'http://ad-din.org/bashundhara-ad-din-medical-college-bamc/about-bamc', now(), now(), false),
    (235, 'BGC Trust Medical College', 'BGCTMC', 'http://bgctmc.medical-colleges.org', now(), now(), false),
    (236, 'Bikrampur Bhuiyan''s Medical College', 'BBMC', 'http://www.bikrampur-bmc.edu.bd', now(), now(), false),
    (237, 'Brahmanbaria Medical College', 'BBMC', 'http://bmchbd.com', now(), now(), false),
    (238, 'Central Medical College', 'CEMEC', 'http://www.cemecbd.com', now(), now(), false),
    (239, 'Chattagram International Medical College', 'CIMCH', 'https://www.cimch.edu.bd', now(), now(), false),
    (240, 'Chattagram Maa-O-Shishu Hospital Medical College', 'CMOSHMC', 'http://www.maa-shishu-ctg.org/of.html', now(), now(), false),
    (241, 'City Medical College', 'CiMC', 'http://cimchbd.com/index.php/home', now(), now(), false),
    (242, 'Community Based Medical College', 'CBMCB', 'http://www.cbmcb.org', now(), now(), false),
    (243, 'Delta Medical College', 'DLMC', 'http://dlmch.edu.bd', now(), now(), false),
    (244, 'Dhaka Central International Medical College', 'DCIMC', 'http://dcimch.com/en', now(), now(), false),
    (245, 'Dhaka Community Medical College', 'DCMC', 'http://dcmch.org', now(), now(), false),
    (246, 'Dhaka National Medical College', 'DNMC', 'https://www.dnmc.edu.bd', now(), now(), false),
    (247, 'Diabetic Association Medical College', 'DAMC', 'https://damcf.edu.bd', now(), now(), false),
    (248, 'Dr. Sirajul Islam Medical College', 'SIMC', 'https://www.drsimc.com', now(), now(), false),
    (249, 'East West Medical College', 'EWMCH', 'https://ewmch.com', now(), now(), false),
    (250, 'Eastern Medical College', 'EMC', 'https://www.emccomilla.com', now(), now(), false),
    (251, 'Enam Medical College and Hospital', 'EMCH', 'https://emcbd.com', now(), now(), false),
    (252, 'Gazi Medical College', 'GMC', 'https://www.gmc.edu.bd', now(), now(), false),
    (253, 'Gonoshasthaya Samaj Vittik Medical College', 'GSVMC', 'http://www.gonosvmc.edu.bd', now(), now(), false),
    (254, 'Green Life Medical College', 'GMCH', 'https://greenlife.edu.bd', now(), now(), false),
    (255, 'Holy Family Red Crescent Medical College', 'HFRCMC', 'http://www.hfrcmc.edu.bd', now(), now(), false),
    (256, 'Ibn Sina Medical College', 'ISMC', 'https://www.ismc.ac.bd', now(), now(), false),
    (257, 'Ibrahim Medical College', 'IMC', 'https://imc.ac.bd', now(), now(), false),
    (258, 'Institute of Applied Health Sciences', 'IAHS', 'http://dnimiahs.ustc.ac.bd', now(), now(), false),
    (259, 'International Medical College', 'IMC', 'https://www.imchbd.com', now(), now(), false),
    (260, 'Islami Bank Medical College', 'IBMC', 'http://ibmcr.com', now(), now(), false),
    (261, 'Jahurul Islam Medical College', 'JIMC', 'https://www.jimedcol.org', now(), now(), false),
    (262, 'Jalalabad Ragib-Rabeya Medical College', 'JRRMC', 'https://www.jrrmc.edu.bd', now(), now(), false),
    (263, 'Khulna City Medical College', 'KCMC', 'http://khulnacitymedicalcollege.edu.bd', now(), now(), false),
    (264, 'Khwaja Yunus Ali Medical College', 'KYAMC', 'https://www.kyamch.org', now(), now(), false),
    (265, 'Kumudini Women''s Medical College', 'KWMC', 'http://www.kwmcbd.org', now(), now(), false),
    (266, 'Mainamoti Medical College', 'MMCH', 'https://www.mainamotimch.com', now(), now(), false),
    (267, 'Marine City Medical College', 'MCMC', 'https://www.mcmchedu.com', now(), now(), false),
    (268, 'Marks Medical College', 'MarksMC', 'http://www.marksgroupbd.com/mmch/index.html', now(), now(), false),
    (269, 'Medical College for Women and Hospital', 'MCW', 'https://www.medicalcollegeforwomen.edu.bd', now(), now(), false),
    (270, 'MH Samorita Medical College', 'MHSMC', 'https://www.mhsamorita.edu.bd', now(), now(), false),
    (271, 'Monno Medical College', 'MoMC', 'https://monnomch.edu.bd', now(), now(), false),
    (272, 'Monowara Sikder Medical College', 'MSMC', 'https://msmc.edu.bd', now(), now(), false),
    (273, 'North Bengal Medical College', 'NBMC', 'http://nbmc-bd.org', now(), now(), false),
    (274, 'North East Medical College', 'NEMC', 'https://www.nemc.edu.bd', now(), now(), false),
    (275, 'Parkview Medical College', 'PMC', 'https://pmch.edu.bd', now(), now(), false),
    (276, 'Popular Medical College', 'PMC', 'https://www.pmch-bd.org', now(), now(), false),
    (277, 'President Abdul Hamid Medical College', 'PAHMC', 'http://www.pahmc.edu.bd', now(), now(), false),
    (278, 'Prime Medical College', 'PMC', 'http://www.pmcbd.org/web', now(), now(), false),
    (279, 'Rangpur Community Medical College', 'RCMC', 'https://rcmc.com.bd', now(), now(), false),
    (280, 'Shahabuddin Medical College', 'SMC', 'https://www.shahabuddinmedical.org', now(), now(), false),
    (281, 'Shaheed Monsur Ali Medical College', 'SMAMC', 'https://smamedicalcollege-bd.com', now(), now(), false),
    (282, 'South Apollo Medical College', 'SAMC', 'https://samcb.edu.bd', now(), now(), false),
    (283, 'Southern Medical College', 'SMCH', 'http://www.smchbd.com', now(), now(), false),
    (284, 'Sylhet Women''s Medical College', 'SWMC', 'https://www.swmc.edu.bd', now(), now(), false),
    (285, 'Tairunnessa Memorial Medical College', 'TMMC', 'https://www.tmmch.com', now(), now(), false),
    (286, 'TMSS Medical College', 'TMC', 'https://tmssmedicalcollege.com', now(), now(), false),
    (287, 'United Medical College', 'UnMC', 'https://umc.edu.bd', now(), now(), false),
    (288, 'Universal Medical College and Hospital, Dhaka', 'UMC', 'https://umc-bd.com', now(), now(), false),
    (289, 'US-Bangla Medical College', 'USBMC', 'https://usbanglamc.com', now(), now(), false),
    (290, 'Uttara Adhunik Medical College', 'UAMC', 'http://www.uamcedu.org', now(), now(), false),
    (291, 'Z. H. Sikder Women''s Medical College', 'ZHSWMC', 'http://sikderhospital.com', now(), now(), false)
ON CONFLICT (id) DO NOTHING;

-- Military medical colleges (7)
INSERT INTO universities (id, name, alias, website, created_at, updated_at, deleted) VALUES
    (292, 'Armed Forces Medical College', 'AFMC', 'https://www.afmc.edu.bd', now(), now(), false),
    (293, 'Army Medical College, Bogura', 'AMCB', 'http://amcbogra.edu.bd', now(), now(), false),
    (294, 'Army Medical College, Chattogram', 'AMCC', 'https://amcc.edu.bd', now(), now(), false),
    (295, 'Army Medical College, Cumilla', 'AMCCu', 'https://www.amccomilla.edu.bd', now(), now(), false),
    (296, 'Army Medical College, Jashore', 'AMCJ', 'https://amcjbd.org', now(), now(), false),
    (297, 'Army Medical College, Rangpur', 'RAMC', 'http://www.ramcbd.com', now(), now(), false),
    (298, 'Navy Medical College, Chattogram', 'NMCC', 'http://nmcc.edu.bd', now(), now(), false)
ON CONFLICT (id) DO NOTHING;
