name: CI/CD with Docker Hub

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Azure VM and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

            # Stop and remove old container if it exists
            docker stop springboot_app || true
            docker rm springboot_app || true

            # Run new container
            docker run -d \
              --name springboot_app \
              --network annonymus_v1_backend \
              -p 8081:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/crud \
              -e SPRING_DATASOURCE_USERNAME=postgres \
              -e SPRING_DATASOURCE_PASSWORD=postgres \
              -e SPRING_PROFILES_ACTIVE=docker \
              ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
          EOF
